output "cluster_id" {
  description = "EKS cluster ID."
  value       = module.eks.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}
resource "local_file" "kubectl_config" {
    content  = "${module.eks.kubeconfig}"
    filename = "kubectl_config"
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = local.cluster_name
}

output "ecr_arn" {
  description = "ecr_arn"
  value       = aws_ecr_repository.my_ecr.arn
}

output "registry_id" {
  description = "registry_id"
  value       = aws_ecr_repository.my_ecr.registry_id
}

output "repository_url" {
  description = "repository_url"
  value       = aws_ecr_repository.my_ecr.repository_url
}
