pipeline {
    agent any
    
    tools {
        terraform 'terraform_plugin'
    }

    parameters {
        string(name: 'environment', defaultValue: 'terraform', description: 'Workspace/environment file to use for deployment')
        booleanParam(name: 'S3', defaultValue: false, description: 'Create-S3 for tfState')
        booleanParam(name: 'destroy', defaultValue: false, description: 'Destroy Terraform build?')
    }
    
    environment {
        AWS_ACCESS_KEY_ID     = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
    }

    stages {

        stage('checkout') {
            steps {
                checkout scm
            }
        }
        
        stage('S3') {
            when {
                equals expected: true, actual: params.S3
            }

            steps {
                dir("Part_2/003_RemoteState") {
                    sh 'pwd'
                    sh 'ls'
                    sh "terraform init -input=false"
                    sh "terraform apply --auto-approve -input=false"
                }
            }
        }

        stage('Apply') {
            when {
                not {
                    equals expected: true, actual: params.destroy
                }
            }
            steps {
                dir("Part_2/003_terraform") {
                    sh 'pwd'
                    sh 'ls'
                    sh "terraform init -input=false -migrate-state"
                    sh "terraform apply --auto-approve -input=false"
                }
            }
        }


        stage('Destroy') {
            when {
                equals expected: true, actual: params.destroy
            }

            steps {
                dir("Part_2/003_terraform") {
                    sh 'pwd'
                    sh "terraform destroy --auto-approve"
                }
            }
        }

    }
}