---
- hosts: all
  become: true
  vars:
  - create_containers: 1
  - default_container_name: docker_test
  - default_container_image: yoni702/final_q1:1.2
  - default_container_command: sleep 1d

  tasks:
    - name: installing git
      package:
         name: git
         state: present
 
    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create docker group
      group:
       name: "docker"
       state: present

    - name: Add the user to groups
      ansible.builtin.user:
       name: ubuntu
       shell: /bin/bash
       groups: sudo,docker
       append: yes

    - name: Pull default Docker image
      docker_image:
        name: "{{default_container_image}}"
        source: pull
   
    - name: Run image
      shell: docker run -d -p 80:80  yoni702/final_q1:1.2
      become: yes
   
   



