---
- hosts: all
  become: true
  vars:
  - create_containers: 1
  - default_container_name: docker_test
  - default_container_image: yoni702/exam:3.3
  - default_container_command: sleep 1d

  tasks:
    - name: installing git
      package:
         name: git
         state: present
 
    #- name: cloning git repo
    #  ansible.builtin.git:
    #        repo: "https://github.com/ishajain140/index_files.git/"
    #        dest: /var/www/html/web


    - name: Install aptitude using apt
      apt: name=aptitude state=latest update_cache=yes force_apt_get=yes

    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present

    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Create docker group
      group:
       name: "docker"
       state: present

    - name: Add the user to groups
      ansible.builtin.user:
       name: ubuntu
       shell: /bin/bash
       groups: sudo,docker
       append: yes

    #- name: Log into DockerHub
      #docker_login:
     # username: 
      #password: 
     # email: 
      #registry: your.private.registry.io
      # docker push yoni702/final_q1:tagname

    - name: Pull default Docker image
      docker_image:
        name: "{{default_container_image}}"
        source: pull

    - name: Create default containers
      docker_container:
        name: "{{ default_container_name }}{{ item }}"
        image: "{{ default_container_image }}"
        command: "{{ default_container_command }}"
        state: present
      with_sequence: count={{ create_containers }}


